import { useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw, ExternalLink } from "lucide-react";
import { supabase } from "@/lib/supabase";
import type { DeliverableStatus, StudioDeliverable } from "@/types/studio";

type Project={id:string;name:string};
type Row=StudioDeliverable & { projects?: Project|null; tasks?: {title:string}|null };
const statuses:DeliverableStatus[]=["DRAFT","IN_PROGRESS","INTERNAL_REVIEW","CLIENT_REVIEW","REVISION_REQUIRED","APPROVED","DELIVERED","ARCHIVED"];

export default function Deliverables(){
 const [rows,setRows]=useState<Row[]>([]),[projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false);
 const [title,setTitle]=useState(""),[projectId,setProjectId]=useState(""),[type,setType]=useState("GENERAL"),[due,setDue]=useState(""),[file,setFile]=useState("");
 const load=async()=>{if(!supabase){setError("Supabase is not configured.");setLoading(false);return}setLoading(true);setError("");const [d,p]=await Promise.all([supabase.from("deliverables").select("id,project_id,task_id,title,description,deliverable_type,status,version,file_url,preview_url,due_date,delivered_at,created_by,created_at,updated_at,projects(id,name),tasks(title)").order("created_at",{ascending:false}),supabase.from("projects").select("id,name").order("name")]);if(d.error||p.error)setError((d.error||p.error)?.message||"Failed to load deliverables");setRows((d.data||[]) as Row[]);setProjects(p.data||[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const create=async()=>{if(!supabase||!title.trim()||!projectId)return;const {error:e}=await supabase.from("deliverables").insert({title:title.trim(),project_id:projectId,deliverable_type:type,file_url:file.trim()||null,due_date:due?new Date(due).toISOString():null,created_by:(await supabase.auth.getUser()).data.user?.id||null});if(e){setError(e.message);return}setTitle("");setProjectId("");setFile("");setDue("");setOpen(false);await load()};
 const update=async(id:string,status:DeliverableStatus)=>{if(!supabase)return;const patch:any={status};if(status==="DELIVERED")patch.delivered_at=new Date().toISOString();const {error:e}=await supabase.from("deliverables").update(patch).eq("id",id);if(e)setError(e.message);else await load()};
 const stats=useMemo(()=>({total:rows.length,review:rows.filter(x=>x.status==="INTERNAL_REVIEW"||x.status==="CLIENT_REVIEW").length,approved:rows.filter(x=>x.status==="APPROVED").length,delivered:rows.filter(x=>x.status==="DELIVERED").length}),[rows]);
 return <div className="min-h-screen bg-[#08090a] text-white"><div className="mx-auto max-w-[1500px] px-6 py-10 md:px-10"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs tracking-[.25em] text-white/30">STUDIO OPERATING SYSTEM</p><h1 className="mt-3 text-4xl font-semibold">Deliverables</h1><p className="mt-2 text-sm text-white/40">Production outputs, versions and delivery status.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-full border border-white/10 p-3 text-white/60"><RefreshCw size={15}/></button><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-medium text-black"><Plus size={15}/>New deliverable</button></div></div>
 <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["TOTAL",stats.total],["IN REVIEW",stats.review],["APPROVED",stats.approved],["DELIVERED",stats.delivered]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><p className="text-[10px] tracking-[.18em] text-white/30">{a}</p><p className="mt-2 text-2xl font-semibold">{b}</p></div>)}</div>
 {error&&<div className="mt-6 rounded-2xl border border-red-400/20 bg-red-400/5 px-5 py-4 text-sm text-red-300">{error}</div>}
 {open&&<div className="mt-6 rounded-3xl border border-white/10 bg-white/[.03] p-6"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Deliverable title" className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"/><select value={projectId} onChange={e=>setProjectId(e.target.value)} className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input value={type} onChange={e=>setType(e.target.value)} placeholder="Type" className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"/><input type="date" value={due} onChange={e=>setDue(e.target.value)} className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"/><input value={file} onChange={e=>setFile(e.target.value)} placeholder="File URL (optional)" className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none md:col-span-2"/></div><div className="mt-4 flex gap-2"><button onClick={()=>void create()} className="rounded-full bg-white px-5 py-2 text-sm text-black">Create</button><button onClick={()=>setOpen(false)} className="rounded-full border border-white/10 px-5 py-2 text-sm text-white/60">Cancel</button></div></div>}
 {loading?<div className="py-24 text-center text-sm text-white/30">Loading deliverables...</div>:<div className="mt-8 overflow-hidden rounded-3xl border border-white/10"><div className="hidden grid-cols-[1.5fr_1fr_.8fr_.7fr_1fr_.7fr] gap-4 border-b border-white/10 bg-white/[.02] px-5 py-4 text-[10px] tracking-[.15em] text-white/30 md:grid"><span>DELIVERABLE</span><span>PROJECT</span><span>TYPE</span><span>VERSION</span><span>STATUS</span><span>FILE</span></div>{rows.map(r=><div key={r.id} className="grid gap-3 border-b border-white/5 px-5 py-5 last:border-0 md:grid-cols-[1.5fr_1fr_.8fr_.7fr_1fr_.7fr] md:items-center"><div><p className="text-sm font-medium">{r.title}</p><p className="mt-1 text-xs text-white/30">{r.tasks?.title||"No task linked"}</p></div><span className="text-xs text-white/50">{r.projects?.name||"—"}</span><span className="text-xs text-white/40">{r.deliverable_type}</span><span className="text-xs text-white/40">v{r.version}</span><select value={r.status} onChange={e=>void update(r.id,e.target.value as DeliverableStatus)} className="rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-[10px] text-white/60">{statuses.map(s=><option key={s}>{s}</option>)}</select>{r.file_url?<a href={r.file_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs text-white/60 hover:text-white">Open <ExternalLink size={12}/></a>:<span className="text-xs text-white/20">No file</span>}</div>)}</div>}</div></div>
}
