import { useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw } from "lucide-react";
import { supabase } from "@/lib/supabase";

const STATUSES = ["LEAD","DISCOVERY","QUOTATION","APPROVED","PLANNING","IN_PRODUCTION","INTERNAL_REVIEW","CLIENT_REVIEW","REVISION","FINAL_DELIVERY","COMPLETED","ARCHIVED"] as const;
const PRIORITIES = ["LOW","MEDIUM","HIGH","URGENT"] as const;
type Project = { id:string; project_code:string; name:string; description:string|null; category:string|null; status:string; priority:string; budget:number|null; deadline:string|null; };

export default function Projects() {
 const [projects,setProjects]=useState<Project[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [open,setOpen]=useState(false);
 const [form,setForm]=useState({project_code:"",name:"",description:"",category:"",priority:"MEDIUM",budget:"",deadline:""});
 const load=async()=>{if(!supabase){setError("Supabase is not configured.");setLoading(false);return;}setLoading(true);const {data,error:e}=await supabase.from("projects").select("id,project_code,name,description,category,status,priority,budget,deadline").order("created_at",{ascending:false});if(e)setError(e.message);else setProjects((data||[]) as Project[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const create=async()=>{if(!supabase||!form.project_code.trim()||!form.name.trim())return;const {error:e}=await supabase.from("projects").insert({project_code:form.project_code.trim(),name:form.name.trim(),description:form.description.trim()||null,category:form.category.trim()||null,priority:form.priority,budget:form.budget?Number(form.budget):null,deadline:form.deadline||null,status:"LEAD"});if(e){setError(e.message);return;}setForm({project_code:"",name:"",description:"",category:"",priority:"MEDIUM",budget:"",deadline:""});setOpen(false);await load()};
 const changeStatus=async(id:string,status:string)=>{if(!supabase)return;const {error:e}=await supabase.from("projects").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(e)setError(e.message);else await load()};
 const summary=useMemo(()=>({active:projects.filter(p=>!['COMPLETED','ARCHIVED'].includes(p.status)).length,production:projects.filter(p=>p.status==='IN_PRODUCTION').length,review:projects.filter(p=>['INTERNAL_REVIEW','CLIENT_REVIEW','REVISION'].includes(p.status)).length}),[projects]);
 return <div className="min-h-screen bg-[#08090a] text-white"><div className="mx-auto max-w-[1500px] px-6 py-10 md:px-10"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs tracking-[.25em] text-white/30">STUDIO OPERATING SYSTEM</p><h1 className="mt-3 text-4xl font-semibold">Projects</h1><p className="mt-2 text-sm text-white/40">Live project pipeline and production control.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-full border border-white/10 p-3 text-white/60"><RefreshCw size={15}/></button><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-medium text-black"><Plus size={15}/>New project</button></div></div>
 <div className="mt-8 grid gap-3 md:grid-cols-3"><Metric label="ACTIVE" value={summary.active}/><Metric label="IN PRODUCTION" value={summary.production}/><Metric label="REVIEW / REVISION" value={summary.review}/></div>
 {error&&<div className="mt-5 rounded-2xl border border-red-400/20 bg-red-400/5 px-5 py-4 text-sm text-red-300">{error}</div>}
 {open&&<div className="mt-6 rounded-3xl border border-white/10 bg-white/[.03] p-6"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{([['project_code','Project code'],['name','Project name'],['category','Category'],['budget','Budget'],['deadline','Deadline']] as const).map(([key,label])=><input key={key} type={key==='deadline'?'datetime-local':key==='budget'?'number':'text'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={label} className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm outline-none"/>)}<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm outline-none">{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" className="min-h-24 rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm outline-none lg:col-span-2"/></div><div className="mt-4 flex gap-2"><button onClick={()=>void create()} className="rounded-full bg-white px-5 py-2 text-sm text-black">Create project</button><button onClick={()=>setOpen(false)} className="rounded-full border border-white/10 px-5 py-2 text-sm text-white/60">Cancel</button></div></div>}
 {loading?<div className="py-24 text-center text-sm text-white/30">Loading projects...</div>:<div className="mt-8 overflow-hidden rounded-3xl border border-white/10"><div className="hidden grid-cols-[1fr_1.5fr_1fr_130px_130px_150px] gap-4 border-b border-white/10 px-5 py-4 text-[10px] tracking-[.16em] text-white/30 md:grid"><span>CODE</span><span>PROJECT</span><span>CATEGORY</span><span>PRIORITY</span><span>DEADLINE</span><span>STATUS</span></div>{projects.map(p=><div key={p.id} className="grid gap-3 border-b border-white/5 px-5 py-5 last:border-0 md:grid-cols-[1fr_1.5fr_1fr_130px_130px_150px] md:items-center"><div className="text-xs text-white/35">{p.project_code}</div><div><div className="text-sm font-medium">{p.name}</div>{p.description&&<div className="mt-1 line-clamp-1 text-xs text-white/30">{p.description}</div>}</div><div className="text-xs text-white/40">{p.category||"—"}</div><div className="text-xs text-white/50">{p.priority}</div><div className="text-xs text-white/40">{p.deadline?new Date(p.deadline).toLocaleDateString():"—"}</div><select value={p.status} onChange={e=>void changeStatus(p.id,e.target.value)} className="rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-[10px] text-white/60">{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>)}</div>}</div></div>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><p className="text-[10px] tracking-[.18em] text-white/30">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>}
