import { useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw } from "lucide-react";
import { supabase } from "@/lib/supabase";
import type { TaskPriority, TaskStatus } from "@/types/studio";

type Task = { id:string; title:string; description:string|null; status:TaskStatus; priority:TaskPriority; deadline:string|null; project_id:string; projects?: { name:string } | null };
const statuses: TaskStatus[] = ["TODO","IN_PROGRESS","BLOCKED","INTERNAL_REVIEW","REVISION_REQUIRED","APPROVED","COMPLETED"];

export default function Tasks() {
  const [tasks,setTasks]=useState<Task[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [open,setOpen]=useState(false);
  const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [priority,setPriority]=useState<TaskPriority>("MEDIUM"); const [projectId,setProjectId]=useState(""); const [projects,setProjects]=useState<{id:string;name:string}[]>([]);
  const load=async()=>{ if(!supabase){setError("Supabase is not configured.");setLoading(false);return;} setLoading(true);setError(""); const [{data,error:e},{data:ps,error:pe}]=await Promise.all([supabase.from("tasks").select("id,title,description,status,priority,deadline,project_id,projects(name)").order("created_at",{ascending:false}),supabase.from("projects").select("id,name").order("name")]); if(e||pe)setError((e||pe)?.message||"Failed to load tasks."); setTasks((data||[]) as Task[]);setProjects(ps||[]);setLoading(false); };
  useEffect(()=>{void load()},[]);
  const createTask=async()=>{if(!supabase||!title.trim()||!projectId)return; const {error:e}=await supabase.from("tasks").insert({title:title.trim(),description:description.trim()||null,priority,project_id:projectId});if(e){setError(e.message);return;}setTitle("");setDescription("");setProjectId("");setOpen(false);await load();};
  const grouped=useMemo(()=>Object.fromEntries(statuses.map(s=>[s,tasks.filter(t=>t.status===s)])) as Record<TaskStatus,Task[]>,[tasks]);
  const move=async(id:string,status:TaskStatus)=>{if(!supabase)return;const {error:e}=await supabase.from("tasks").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(e)setError(e.message);else await load();};
  return <div className="min-h-screen bg-[#08090a] text-white"><div className="mx-auto max-w-[1600px] px-6 py-10 md:px-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs tracking-[.25em] text-white/30">STUDIO OPERATING SYSTEM</p><h1 className="mt-3 text-4xl font-semibold">Tasks</h1><p className="mt-2 text-sm text-white/40">Live production task board.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-full border border-white/10 p-3 text-white/60"><RefreshCw size={15}/></button><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-medium text-black"><Plus size={15}/>New task</button></div></div>{error&&<div className="mt-6 rounded-2xl border border-red-400/20 bg-red-400/5 px-5 py-4 text-sm text-red-300">{error}</div>}
  {open&&<div className="mt-6 rounded-3xl border border-white/10 bg-white/[.03] p-6"><div className="grid gap-4 md:grid-cols-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Task title" className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"/><select value={projectId} onChange={e=>setProjectId(e.target.value)} className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value as TaskPriority)} className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none">{["LOW","MEDIUM","HIGH","URGENT"].map(p=><option key={p}>{p}</option>)}</select><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description (optional)" className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none"/></div><div className="mt-4 flex gap-2"><button onClick={()=>void createTask()} className="rounded-full bg-white px-5 py-2 text-sm text-black">Create</button><button onClick={()=>setOpen(false)} className="rounded-full border border-white/10 px-5 py-2 text-sm text-white/60">Cancel</button></div></div>}
  {loading?<div className="py-24 text-center text-sm text-white/30">Loading tasks...</div>:<div className="mt-8 grid gap-4 overflow-x-auto pb-4 lg:grid-cols-4 xl:grid-cols-7">{statuses.map(status=><div key={status} className="min-w-[220px] rounded-2xl border border-white/10 bg-white/[.02] p-3"><div className="mb-4 flex items-center justify-between"><span className="text-[10px] tracking-[.16em] text-white/40">{status.replaceAll("_"," ")}</span><span className="text-xs text-white/20">{grouped[status].length}</span></div><div className="space-y-3">{grouped[status].map(t=><article key={t.id} className="rounded-xl border border-white/10 bg-[#0d0f10] p-4"><h3 className="text-sm font-medium">{t.title}</h3><p className="mt-1 text-[10px] text-white/30">{t.projects?.name||"No project"}</p><p className="mt-3 text-[10px] text-white/40">{t.priority}</p><select value={t.status} onChange={e=>void move(t.id,e.target.value as TaskStatus)} className="mt-3 w-full rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-[10px] text-white/60">{statuses.map(s=><option key={s}>{s}</option>)}</select></article>)}</div></div>)}</div>}</div></div>;
}
